xataio/mdx-blog

company-offsite-milan-2023.mdx
probably should have done this with the last PR
=> Fix image URL for offsite blog & publish

replica-identity-full-performance.mdx
Only whitespace in code components was touched.
=> fix whitespace in blog post

branching-benefits-git-databases.mdx, datetime-picker.mdx, offsite-for-a-fully-remote-team.mdx, xataform-is-here.mdx
Fixes images that weren't using the correct MDX syntax or have broken src.
=> fix images

datetime-picker.mdx
Had a dupe from the conversion
=> Fix uneccessary video

replica-identity-full-performance.mdx
I've applied some of the changes from #29 selectively. Many thanks for the detailed review and edits @joan-ing , please have a look and see if I missed anything important.
=> Improvements for the Replica Identity blog post

server-actions-databases-data-handling.mdx
Fix from https://github.com/xataio/mdx-blog/pull/35
=> Typo in blog

.github/workflows/preview.yml
Merge after https://github.com/xataio/mdx-docs merges
=> Change github action to use main branches if env not set

postgres-full-text-search-engine.mdx
=> Fix dark vader to darth vader 🤦

sql-mysql-postgresql-nosql.mdx
Fixes broken image in blog index
=> blog image

database-schema-design.mdx
Fix for image display of https://xata.io/blog/database-schema-design
=> Set fixed height & width on image

csv-import-export.mdx, launch-week-august-2023.mdx
=> Publish launch blog posts

launch-week-august-2023.mdx
=> Added a link to twitter where people can reply

.github/workflows/preview.yml
- Add an alias for the PR xata-docs-pr-105.vercel.app
- Show the comment when triggering the deploy with the inspect url
- Update the comment when the deploy has finished
=> Update workflow to have preview on PRs

keyword-vs-semantic-search-chatgpt.mdx, openapi-typesafe-react-query-hooks.mdx, postgres-full-text-search-engine.mdx, postgres-full-text-search-postgres-vs-elasticsearch.mdx, replica-identity-full-performance.mdx
Added as a sample to one blog post. We can discuss if we want to extend this further.
=> Paragraph for introducing xata in blog posts

.eslintignore, .github/workflows/lint.yml, .prettierignore, announcing-python-sdk-ga.mdx, database-schema-design.mdx, xata-workers-client-side-database.mdx, xatabyte-database-indexing.mdx
- Enforce prettier rules in github action for mdx files.
I've manually visually diffed all the changed blog posts against xata.io/blog
=> Enable prettier for `.mdx` files in github action

introducing-pgroll.mdx
=> Undoable -> reversible

blog.schema.yaml, introducing-pgroll.mdx
This pull request defines the format for linting the tags.
=> Define the `tags` linting format

datetime-picker.mdx
I'm testing that our website is deploying changes properly. I will revert this change shortly.
=> Testing a tiny change to check website is deploying properly

datetime-picker.mdx
=> Revert "Testing a tiny change to check website is deploying properly"

.github/workflows/deploy.yml
When a commit is pushed to the main branch we trigger a production vercel deploy of the 'website.
=> Deploy Vercel website on push to `main` branch

datetime-picker.mdx
=> Testing: Revert "Revert "Testing a tiny change to check website is deploying properly""

community-spotlight-simplified-architecture-hotel.mdx
=> Fix a couple of typos

xata-holiday-hackathon.mdx
=> change date

feature-flags-tutorial.mdx
=> remove duplicate content

cloudflare-integration.mdx
=> Publish cloudflare blog

build-image-gallery-astro-cloudflare.mdx
=> Update date for latest blog

build-content-management-system.mdx
=> fixing link labels

branching-benefits-git-databases.mdx, chatgpt-on-your-data.mdx, community-spotlight-reducing-search-response-time-by-99-percent.mdx, file-attachments.mdx, indexing-files-with-python.mdx, introducing-pgroll.mdx, keyword-vs-semantic-search-chatgpt.mdx, pgroll-internals.mdx, postgres-full-text-search-postgres-vs-elasticsearch.mdx, postgres-schema-changes-pita.mdx, preview-deployment-vercel-xata.mdx, rag-vector-sveltekit-xata.mdx, search-three-ways.mdx, sql-over-http.mdx, workflow-github-vercel-netlify-xata.mdx, zero-downtime-schema-migrations-postgresql.mdx
This PR adds tags for feature-related blog post organization for the new website:
=> Add tags for feature-related blog post organization

build-image-gallery-astro-cloudflare.mdx
Add `fpFileAttachments` tag to `chatgpt-on-your-data` post. 
=> Add `fpFileAttachments` tag

introducing-pgroll.mdx, pgroll-internals.mdx, zero-downtime-schema-migrations-postgresql.mdx
@CezzaineZ @snide @miukimiu quick new tag to populate this https://xata.io/blog/tags/oss/rss.xml
=> tagging a few blogs with oss for the subscription flow

prisma-integration.mdx
=> remove redundant line

why_postgres.mdx
=> Add custom ogImage for the blog post

easter-egg-hunt.mdx
Adding a daily hint update to the blog: https://docs.google.com/document/d/18M6lXaG4KYC_H6JZVhKMTNG2TE9J9c2LXPy4zWSttiQ/edit
=> Appending riddle hints to easter egg blog

usage-insights-launch.mdx
follow up of https://github.com/xataio/mdx-blog/pull/224 to publish on launch day.
=> [Merge Wednesday] Publish usage metrics blog

usage-insights-launch.mdx
=> Break long lines

easter-egg-hunt.mdx
Changed Easter to a proper noun while I was at it.
=> Easter egg hint, day 3

easter-egg-hunt.mdx
Adds a hint for the easter egg hunt, day 4 on the blog.
=> [Merge Thursday] Update hint for easter egg, day 4

easter-egg-hunt.mdx
=> Hint for day 5

usage-insights-launch.mdx
=> Usage blog post typo fix

easter-egg-hunt.mdx
=> Adding Itsuki to easter egg blog

why_postgres.mdx
See if having @tsg as the only author would trigger the planet postgres blog
=> trying to trigger rss feed from planet postgres

connecting-creating-collaborating.mdx
fixing og image and using Elizabets design
=> updated og and list image for evora blog

geographically-distributed-postgresql.mdx
I forgot that we need this for RSS.
=> Add author email for RSS

prisma-integration.mdx
Updates the Prisma blog post with migration info
=> Prisma migration notes

postgres-free-tier.mdx
=> Update blog post with date and tags

postgres-free-tier.mdx
=> Fix wrong info about Neon free tier

postgresql-dedicated-clusters-beta.mdx
=> chore: fix typos in dc blog

pgzx-update-0.2.0.mdx
- https://xata.io/blog/pgzx-update-0.2.0
=> Publish pgzx update 0.2.0

website-deep-dive.mdx
Following the work on https://github.com/xataio/frontend-next/pull/3796
=> Add twitter creator field

pgdump-is-not-a-backup-tool.mdx
- This PR adds blockquotes to the pgdump post
Test it here: https://xata-blog-pr-310.vercel.app/blog/pgdump-is-not-a-backup-tool
=> Add blockquotes to pgdump post

webhooks-with-pgstream.mdx
- This PR fixes an image that has incorrect file type
=> Fix image for "Postgres webhooks with pgstream"

pgconfeu-recap.mdx
=> Update og image for PGConfEU recap blog

maintainable-podcast.mdx
=> Fix the missing image folder

anatomy-of-locks-reduce.mdx
-
Direct link to blog on preview site: https://xata-blog-pr-346.vercel.app/blog/anatomy-of-locks-reduce
- \[x] Release on: \<mm/dd/yy>
- \[x] OG image included
=> Add Anatomy of Locks: Reducing Locking Impact blog

anatomy-of-locks-reduce.mdx
- This PR resolves an MDX issue that was preventing Vercel from building previews and merging in the website repository.
=> Fix blog preview

whats-new-in-pgroll-0-9-0.mdx
=> Fix date for pgroll 0.9 blog post

whats-new-in-pgroll-0-11-0.mdx
- This is the inital draft of the next release of `pgroll`.
- \[ ] Release on: 04/10/2025
=> Add `pgroll` `v0.11` release post
